"use client";

import { useEffect, useState } from "react";
import { renderCode, verticalBarcode, type CodeKind } from "@/lib/codes";

/**
 * Thin wrappers that turn an encoder call into inline SVG markup. The SVG is
 * generated by bwip-js from a fixed string, which is why dangerouslySetInnerHTML
 * is safe here: no user text reaches the DOM as markup, only path data does.
 *
 * `data-code-ready` is what the exporter waits on. It reads "true" on success
 * and "error" on failure, so a broken encode can never hold the export open
 * until its timeout, and never silently ships a blank box.
 */

type Status = "pending" | "ready" | "error";

interface Cached {
  /** Which input produced this result. */
  signature: string;
  svg: string | null;
  status: Status;
}

const EMPTY: Cached = { signature: "", svg: null, status: "pending" };

/**
 * The stored result carries the signature that produced it, and staleness is
 * worked out during render rather than by resetting state inside the effect.
 * Resetting in the effect body is what triggers the cascading render React
 * warns about, and it is avoidable: if the signature has moved on, the result
 * in hand is simply not the one being asked for.
 */
function useCode(run: () => Promise<{ svg: string }>, signature: string): Cached {
  const [cached, setCached] = useState<Cached>(EMPTY);

  useEffect(() => {
    let live = true;

    run()
      .then((result) => {
        if (live) setCached({ signature, svg: result.svg, status: "ready" });
      })
      .catch((cause) => {
        if (!live) return;
        // Worth surfacing. A silent catch here is what hid the Data Matrix bug.
        console.error("Code generation failed", cause);
        setCached({ signature, svg: null, status: "error" });
      });

    return () => {
      live = false;
    };
    // `run` closes over the same values `signature` is built from.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [signature]);

  return cached.signature === signature ? cached : EMPTY;
}

function Frame({ state, className }: { state: Cached; className?: string }) {
  return (
    <div
      className={className}
      data-code-ready={state.status === "ready" ? "true" : state.status === "error" ? "error" : "false"}
      style={{ lineHeight: 0 }}
      dangerouslySetInnerHTML={{ __html: state.svg ?? "" }}
    />
  );
}

export function DataCode({
  value,
  kind = "datamatrix",
  className,
}: {
  value: string;
  kind?: CodeKind;
  className?: string;
}) {
  const state = useCode(() => renderCode(kind, value), `${kind}::${value}`);
  return <Frame state={state} className={className} />;
}

export function VerticalBarcode({ value, className }: { value: string; className?: string }) {
  const state = useCode(() => verticalBarcode(value), `code128::${value}`);
  return <Frame state={state} className={className} />;
}
